language: java
sudo: false
before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import || true
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
matrix:
  include:
# OpenJDK
    - name: 'OpenJDK 7'
      jdk: openjdk7
    - name: 'OpenJDK 8'
      jdk: openjdk8
    - name: 'OpenJDK 11'
      install: . ./install-jdk.sh -L GPL -F 11
    - name: 'OpenJDK 12'
      install: . ./install-jdk.sh -L GPL -F 12
# Oracle JDK
    - name: 'Oracle JDK 8'
      jdk: oraclejdk8
    - name: 'Oracle JDK 11'
      jdk: oraclejdk11
    - name: 'Oracle JDK 12'
      install: . ./install-jdk.sh -L BCL -F 12
  allow_failures:
    - name: 'OpenJDK 7'
    - name: 'OpenJDK 12'
    - name: 'Oracle JDK 8' # See https://travis-ci.community/t/expected-feature-release-number-in-range-of-9-to-12-but-got-8-installing-oraclejdk8/1345/14
    - name: 'Oracle JDK 11' # See https://travis-ci.community/t/cannot-install-oracle-jdk-11/3892/3
    - name: 'Oracle JDK 12'
services:
  - docker
notifications:
  slack:
    on_success: change
    on_failure: change
    rooms:
      - secure: MkRPjhMDkLMT0tKhSzSAEEdLxKlFrcEw00FBgpcpIl50kSpe3gxCJsm2bz5+LySblCfY1nI5D1+R++eB5cxJzgZvEBWIXQnGJVAV+X7WW1CI1FBZlv6FNLBe5gVPPzo5kIIM1g3o7AaERcraHK9h9S9N8cpnBRHe+Xf6wTRqmwo=
      - secure: iRd6XcgHGFSJ/eS1ZwCUgUVTK0a+JAPmyPEx/OdFbma6DvF8WBhWtW5Q1dyrjQ3JWU8DW2Att9jRnGHd9F5wWWcykxYbD9DXrlfqCZpec9pHzEMAud9MG1PqK0d3y2oyjwps/fQ092PJcn9/y7zX6tzdVWKaKUe4iRDs1u1ehUo=
install:
  - mvn --settings .maven.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
deploy:
  - provider: script
    script: make docker-build && make docker-push
    skip_cleanup: true
    on:
      tags: true
      jdk: openjdk8
  - provider: script
    script: mvn clean deploy --settings .maven.xml -DskipTests=true -B -U -Prelease
    skip_cleanup: true
    on:
      tags: true
      jdk: openjdk8
